// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bug_list/internal/models/model"
)

func newBugRemark(db *gorm.DB, opts ...gen.DOOption) bugRemark {
	_bugRemark := bugRemark{}

	_bugRemark.bugRemarkDo.UseDB(db, opts...)
	_bugRemark.bugRemarkDo.UseModel(&model.BugRemark{})

	tableName := _bugRemark.bugRemarkDo.TableName()
	_bugRemark.ALL = field.NewAsterisk(tableName)
	_bugRemark.RemarkID = field.NewInt64(tableName, "remark_id")
	_bugRemark.BugID = field.NewInt64(tableName, "bug_id")
	_bugRemark.UserID = field.NewInt64(tableName, "user_id")
	_bugRemark.Remark = field.NewString(tableName, "remark")
	_bugRemark.CreatedAt = field.NewTime(tableName, "created_at")

	_bugRemark.fillFieldMap()

	return _bugRemark
}

type bugRemark struct {
	bugRemarkDo

	ALL       field.Asterisk
	RemarkID  field.Int64
	BugID     field.Int64
	UserID    field.Int64
	Remark    field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (b bugRemark) Table(newTableName string) *bugRemark {
	b.bugRemarkDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bugRemark) As(alias string) *bugRemark {
	b.bugRemarkDo.DO = *(b.bugRemarkDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bugRemark) updateTableName(table string) *bugRemark {
	b.ALL = field.NewAsterisk(table)
	b.RemarkID = field.NewInt64(table, "remark_id")
	b.BugID = field.NewInt64(table, "bug_id")
	b.UserID = field.NewInt64(table, "user_id")
	b.Remark = field.NewString(table, "remark")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *bugRemark) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bugRemark) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 5)
	b.fieldMap["remark_id"] = b.RemarkID
	b.fieldMap["bug_id"] = b.BugID
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["remark"] = b.Remark
	b.fieldMap["created_at"] = b.CreatedAt
}

func (b bugRemark) clone(db *gorm.DB) bugRemark {
	b.bugRemarkDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bugRemark) replaceDB(db *gorm.DB) bugRemark {
	b.bugRemarkDo.ReplaceDB(db)
	return b
}

type bugRemarkDo struct{ gen.DO }

type IBugRemarkDo interface {
	gen.SubQuery
	Debug() IBugRemarkDo
	WithContext(ctx context.Context) IBugRemarkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBugRemarkDo
	WriteDB() IBugRemarkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBugRemarkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBugRemarkDo
	Not(conds ...gen.Condition) IBugRemarkDo
	Or(conds ...gen.Condition) IBugRemarkDo
	Select(conds ...field.Expr) IBugRemarkDo
	Where(conds ...gen.Condition) IBugRemarkDo
	Order(conds ...field.Expr) IBugRemarkDo
	Distinct(cols ...field.Expr) IBugRemarkDo
	Omit(cols ...field.Expr) IBugRemarkDo
	Join(table schema.Tabler, on ...field.Expr) IBugRemarkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBugRemarkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBugRemarkDo
	Group(cols ...field.Expr) IBugRemarkDo
	Having(conds ...gen.Condition) IBugRemarkDo
	Limit(limit int) IBugRemarkDo
	Offset(offset int) IBugRemarkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBugRemarkDo
	Unscoped() IBugRemarkDo
	Create(values ...*model.BugRemark) error
	CreateInBatches(values []*model.BugRemark, batchSize int) error
	Save(values ...*model.BugRemark) error
	First() (*model.BugRemark, error)
	Take() (*model.BugRemark, error)
	Last() (*model.BugRemark, error)
	Find() ([]*model.BugRemark, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BugRemark, err error)
	FindInBatches(result *[]*model.BugRemark, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BugRemark) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBugRemarkDo
	Assign(attrs ...field.AssignExpr) IBugRemarkDo
	Joins(fields ...field.RelationField) IBugRemarkDo
	Preload(fields ...field.RelationField) IBugRemarkDo
	FirstOrInit() (*model.BugRemark, error)
	FirstOrCreate() (*model.BugRemark, error)
	FindByPage(offset int, limit int) (result []*model.BugRemark, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBugRemarkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b bugRemarkDo) Debug() IBugRemarkDo {
	return b.withDO(b.DO.Debug())
}

func (b bugRemarkDo) WithContext(ctx context.Context) IBugRemarkDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bugRemarkDo) ReadDB() IBugRemarkDo {
	return b.Clauses(dbresolver.Read)
}

func (b bugRemarkDo) WriteDB() IBugRemarkDo {
	return b.Clauses(dbresolver.Write)
}

func (b bugRemarkDo) Session(config *gorm.Session) IBugRemarkDo {
	return b.withDO(b.DO.Session(config))
}

func (b bugRemarkDo) Clauses(conds ...clause.Expression) IBugRemarkDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bugRemarkDo) Returning(value interface{}, columns ...string) IBugRemarkDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bugRemarkDo) Not(conds ...gen.Condition) IBugRemarkDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bugRemarkDo) Or(conds ...gen.Condition) IBugRemarkDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bugRemarkDo) Select(conds ...field.Expr) IBugRemarkDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bugRemarkDo) Where(conds ...gen.Condition) IBugRemarkDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bugRemarkDo) Order(conds ...field.Expr) IBugRemarkDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bugRemarkDo) Distinct(cols ...field.Expr) IBugRemarkDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bugRemarkDo) Omit(cols ...field.Expr) IBugRemarkDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bugRemarkDo) Join(table schema.Tabler, on ...field.Expr) IBugRemarkDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bugRemarkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBugRemarkDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bugRemarkDo) RightJoin(table schema.Tabler, on ...field.Expr) IBugRemarkDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bugRemarkDo) Group(cols ...field.Expr) IBugRemarkDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bugRemarkDo) Having(conds ...gen.Condition) IBugRemarkDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bugRemarkDo) Limit(limit int) IBugRemarkDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bugRemarkDo) Offset(offset int) IBugRemarkDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bugRemarkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBugRemarkDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bugRemarkDo) Unscoped() IBugRemarkDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bugRemarkDo) Create(values ...*model.BugRemark) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bugRemarkDo) CreateInBatches(values []*model.BugRemark, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bugRemarkDo) Save(values ...*model.BugRemark) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bugRemarkDo) First() (*model.BugRemark, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BugRemark), nil
	}
}

func (b bugRemarkDo) Take() (*model.BugRemark, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BugRemark), nil
	}
}

func (b bugRemarkDo) Last() (*model.BugRemark, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BugRemark), nil
	}
}

func (b bugRemarkDo) Find() ([]*model.BugRemark, error) {
	result, err := b.DO.Find()
	return result.([]*model.BugRemark), err
}

func (b bugRemarkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BugRemark, err error) {
	buf := make([]*model.BugRemark, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bugRemarkDo) FindInBatches(result *[]*model.BugRemark, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bugRemarkDo) Attrs(attrs ...field.AssignExpr) IBugRemarkDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bugRemarkDo) Assign(attrs ...field.AssignExpr) IBugRemarkDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bugRemarkDo) Joins(fields ...field.RelationField) IBugRemarkDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bugRemarkDo) Preload(fields ...field.RelationField) IBugRemarkDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bugRemarkDo) FirstOrInit() (*model.BugRemark, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BugRemark), nil
	}
}

func (b bugRemarkDo) FirstOrCreate() (*model.BugRemark, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BugRemark), nil
	}
}

func (b bugRemarkDo) FindByPage(offset int, limit int) (result []*model.BugRemark, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bugRemarkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bugRemarkDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bugRemarkDo) Delete(models ...*model.BugRemark) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bugRemarkDo) withDO(do gen.Dao) *bugRemarkDo {
	b.DO = *do.(*gen.DO)
	return b
}
