// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bug_list/internal/models/model"
)

func newBug(db *gorm.DB, opts ...gen.DOOption) bug {
	_bug := bug{}

	_bug.bugDo.UseDB(db, opts...)
	_bug.bugDo.UseModel(&model.Bug{})

	tableName := _bug.bugDo.TableName()
	_bug.ALL = field.NewAsterisk(tableName)
	_bug.BugID = field.NewInt64(tableName, "bug_id")
	_bug.ProjID = field.NewInt64(tableName, "proj_id")
	_bug.Title = field.NewString(tableName, "title")
	_bug.Description = field.NewString(tableName, "description")
	_bug.Status = field.NewString(tableName, "status")
	_bug.Priority = field.NewString(tableName, "priority")
	_bug.ReportedBy = field.NewInt64(tableName, "reported_by")
	_bug.AssignedTo = field.NewInt64(tableName, "assigned_to")
	_bug.CreatedAt = field.NewTime(tableName, "created_at")
	_bug.CreateBy = field.NewInt64(tableName, "create_by")
	_bug.ModifiedAt = field.NewTime(tableName, "modified_at")
	_bug.ModifiedBy = field.NewInt64(tableName, "modified_by")
	_bug.ResolvedAt = field.NewTime(tableName, "resolved_at")

	_bug.fillFieldMap()

	return _bug
}

type bug struct {
	bugDo

	ALL         field.Asterisk
	BugID       field.Int64
	ProjID      field.Int64
	Title       field.String
	Description field.String
	Status      field.String
	Priority    field.String
	ReportedBy  field.Int64
	AssignedTo  field.Int64
	CreatedAt   field.Time
	CreateBy    field.Int64
	ModifiedAt  field.Time
	ModifiedBy  field.Int64
	ResolvedAt  field.Time

	fieldMap map[string]field.Expr
}

func (b bug) Table(newTableName string) *bug {
	b.bugDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bug) As(alias string) *bug {
	b.bugDo.DO = *(b.bugDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bug) updateTableName(table string) *bug {
	b.ALL = field.NewAsterisk(table)
	b.BugID = field.NewInt64(table, "bug_id")
	b.ProjID = field.NewInt64(table, "proj_id")
	b.Title = field.NewString(table, "title")
	b.Description = field.NewString(table, "description")
	b.Status = field.NewString(table, "status")
	b.Priority = field.NewString(table, "priority")
	b.ReportedBy = field.NewInt64(table, "reported_by")
	b.AssignedTo = field.NewInt64(table, "assigned_to")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.CreateBy = field.NewInt64(table, "create_by")
	b.ModifiedAt = field.NewTime(table, "modified_at")
	b.ModifiedBy = field.NewInt64(table, "modified_by")
	b.ResolvedAt = field.NewTime(table, "resolved_at")

	b.fillFieldMap()

	return b
}

func (b *bug) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bug) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 13)
	b.fieldMap["bug_id"] = b.BugID
	b.fieldMap["proj_id"] = b.ProjID
	b.fieldMap["title"] = b.Title
	b.fieldMap["description"] = b.Description
	b.fieldMap["status"] = b.Status
	b.fieldMap["priority"] = b.Priority
	b.fieldMap["reported_by"] = b.ReportedBy
	b.fieldMap["assigned_to"] = b.AssignedTo
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["create_by"] = b.CreateBy
	b.fieldMap["modified_at"] = b.ModifiedAt
	b.fieldMap["modified_by"] = b.ModifiedBy
	b.fieldMap["resolved_at"] = b.ResolvedAt
}

func (b bug) clone(db *gorm.DB) bug {
	b.bugDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bug) replaceDB(db *gorm.DB) bug {
	b.bugDo.ReplaceDB(db)
	return b
}

type bugDo struct{ gen.DO }

type IBugDo interface {
	gen.SubQuery
	Debug() IBugDo
	WithContext(ctx context.Context) IBugDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBugDo
	WriteDB() IBugDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBugDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBugDo
	Not(conds ...gen.Condition) IBugDo
	Or(conds ...gen.Condition) IBugDo
	Select(conds ...field.Expr) IBugDo
	Where(conds ...gen.Condition) IBugDo
	Order(conds ...field.Expr) IBugDo
	Distinct(cols ...field.Expr) IBugDo
	Omit(cols ...field.Expr) IBugDo
	Join(table schema.Tabler, on ...field.Expr) IBugDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBugDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBugDo
	Group(cols ...field.Expr) IBugDo
	Having(conds ...gen.Condition) IBugDo
	Limit(limit int) IBugDo
	Offset(offset int) IBugDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBugDo
	Unscoped() IBugDo
	Create(values ...*model.Bug) error
	CreateInBatches(values []*model.Bug, batchSize int) error
	Save(values ...*model.Bug) error
	First() (*model.Bug, error)
	Take() (*model.Bug, error)
	Last() (*model.Bug, error)
	Find() ([]*model.Bug, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Bug, err error)
	FindInBatches(result *[]*model.Bug, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Bug) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBugDo
	Assign(attrs ...field.AssignExpr) IBugDo
	Joins(fields ...field.RelationField) IBugDo
	Preload(fields ...field.RelationField) IBugDo
	FirstOrInit() (*model.Bug, error)
	FirstOrCreate() (*model.Bug, error)
	FindByPage(offset int, limit int) (result []*model.Bug, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBugDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b bugDo) Debug() IBugDo {
	return b.withDO(b.DO.Debug())
}

func (b bugDo) WithContext(ctx context.Context) IBugDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bugDo) ReadDB() IBugDo {
	return b.Clauses(dbresolver.Read)
}

func (b bugDo) WriteDB() IBugDo {
	return b.Clauses(dbresolver.Write)
}

func (b bugDo) Session(config *gorm.Session) IBugDo {
	return b.withDO(b.DO.Session(config))
}

func (b bugDo) Clauses(conds ...clause.Expression) IBugDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bugDo) Returning(value interface{}, columns ...string) IBugDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bugDo) Not(conds ...gen.Condition) IBugDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bugDo) Or(conds ...gen.Condition) IBugDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bugDo) Select(conds ...field.Expr) IBugDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bugDo) Where(conds ...gen.Condition) IBugDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bugDo) Order(conds ...field.Expr) IBugDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bugDo) Distinct(cols ...field.Expr) IBugDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bugDo) Omit(cols ...field.Expr) IBugDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bugDo) Join(table schema.Tabler, on ...field.Expr) IBugDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bugDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBugDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bugDo) RightJoin(table schema.Tabler, on ...field.Expr) IBugDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bugDo) Group(cols ...field.Expr) IBugDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bugDo) Having(conds ...gen.Condition) IBugDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bugDo) Limit(limit int) IBugDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bugDo) Offset(offset int) IBugDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bugDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBugDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bugDo) Unscoped() IBugDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bugDo) Create(values ...*model.Bug) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bugDo) CreateInBatches(values []*model.Bug, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bugDo) Save(values ...*model.Bug) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bugDo) First() (*model.Bug, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bug), nil
	}
}

func (b bugDo) Take() (*model.Bug, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bug), nil
	}
}

func (b bugDo) Last() (*model.Bug, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bug), nil
	}
}

func (b bugDo) Find() ([]*model.Bug, error) {
	result, err := b.DO.Find()
	return result.([]*model.Bug), err
}

func (b bugDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Bug, err error) {
	buf := make([]*model.Bug, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bugDo) FindInBatches(result *[]*model.Bug, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bugDo) Attrs(attrs ...field.AssignExpr) IBugDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bugDo) Assign(attrs ...field.AssignExpr) IBugDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bugDo) Joins(fields ...field.RelationField) IBugDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bugDo) Preload(fields ...field.RelationField) IBugDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bugDo) FirstOrInit() (*model.Bug, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bug), nil
	}
}

func (b bugDo) FirstOrCreate() (*model.Bug, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bug), nil
	}
}

func (b bugDo) FindByPage(offset int, limit int) (result []*model.Bug, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bugDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bugDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bugDo) Delete(models ...*model.Bug) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bugDo) withDO(do gen.Dao) *bugDo {
	b.DO = *do.(*gen.DO)
	return b
}
