// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	Bug              *bug
	BugRemark        *bugRemark
	Project          *project
	ProjectMember    *projectMember
	RoleRef          *roleRef
	User             *user
	UserRefreshToken *userRefreshToken
	UserRole         *userRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Bug = &Q.Bug
	BugRemark = &Q.BugRemark
	Project = &Q.Project
	ProjectMember = &Q.ProjectMember
	RoleRef = &Q.RoleRef
	User = &Q.User
	UserRefreshToken = &Q.UserRefreshToken
	UserRole = &Q.UserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		Bug:              newBug(db, opts...),
		BugRemark:        newBugRemark(db, opts...),
		Project:          newProject(db, opts...),
		ProjectMember:    newProjectMember(db, opts...),
		RoleRef:          newRoleRef(db, opts...),
		User:             newUser(db, opts...),
		UserRefreshToken: newUserRefreshToken(db, opts...),
		UserRole:         newUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Bug              bug
	BugRemark        bugRemark
	Project          project
	ProjectMember    projectMember
	RoleRef          roleRef
	User             user
	UserRefreshToken userRefreshToken
	UserRole         userRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Bug:              q.Bug.clone(db),
		BugRemark:        q.BugRemark.clone(db),
		Project:          q.Project.clone(db),
		ProjectMember:    q.ProjectMember.clone(db),
		RoleRef:          q.RoleRef.clone(db),
		User:             q.User.clone(db),
		UserRefreshToken: q.UserRefreshToken.clone(db),
		UserRole:         q.UserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Bug:              q.Bug.replaceDB(db),
		BugRemark:        q.BugRemark.replaceDB(db),
		Project:          q.Project.replaceDB(db),
		ProjectMember:    q.ProjectMember.replaceDB(db),
		RoleRef:          q.RoleRef.replaceDB(db),
		User:             q.User.replaceDB(db),
		UserRefreshToken: q.UserRefreshToken.replaceDB(db),
		UserRole:         q.UserRole.replaceDB(db),
	}
}

type queryCtx struct {
	Bug              IBugDo
	BugRemark        IBugRemarkDo
	Project          IProjectDo
	ProjectMember    IProjectMemberDo
	RoleRef          IRoleRefDo
	User             IUserDo
	UserRefreshToken IUserRefreshTokenDo
	UserRole         IUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Bug:              q.Bug.WithContext(ctx),
		BugRemark:        q.BugRemark.WithContext(ctx),
		Project:          q.Project.WithContext(ctx),
		ProjectMember:    q.ProjectMember.WithContext(ctx),
		RoleRef:          q.RoleRef.WithContext(ctx),
		User:             q.User.WithContext(ctx),
		UserRefreshToken: q.UserRefreshToken.WithContext(ctx),
		UserRole:         q.UserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
