// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bug_list/internal/models/model"
)

func newRoleRef(db *gorm.DB, opts ...gen.DOOption) roleRef {
	_roleRef := roleRef{}

	_roleRef.roleRefDo.UseDB(db, opts...)
	_roleRef.roleRefDo.UseModel(&model.RoleRef{})

	tableName := _roleRef.roleRefDo.TableName()
	_roleRef.ALL = field.NewAsterisk(tableName)
	_roleRef.RoleID = field.NewInt64(tableName, "role_id")
	_roleRef.RoleName = field.NewString(tableName, "role_name")
	_roleRef.Description = field.NewString(tableName, "description")
	_roleRef.RoleSeq = field.NewInt64(tableName, "role_seq")
	_roleRef.CreatedAt = field.NewTime(tableName, "created_at")
	_roleRef.ModifiedAt = field.NewTime(tableName, "modified_at")
	_roleRef.CreateBy = field.NewInt64(tableName, "create_by")
	_roleRef.ModifiedBy = field.NewInt64(tableName, "modified_by")

	_roleRef.fillFieldMap()

	return _roleRef
}

type roleRef struct {
	roleRefDo

	ALL         field.Asterisk
	RoleID      field.Int64
	RoleName    field.String
	Description field.String
	RoleSeq     field.Int64
	CreatedAt   field.Time
	ModifiedAt  field.Time
	CreateBy    field.Int64
	ModifiedBy  field.Int64

	fieldMap map[string]field.Expr
}

func (r roleRef) Table(newTableName string) *roleRef {
	r.roleRefDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roleRef) As(alias string) *roleRef {
	r.roleRefDo.DO = *(r.roleRefDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roleRef) updateTableName(table string) *roleRef {
	r.ALL = field.NewAsterisk(table)
	r.RoleID = field.NewInt64(table, "role_id")
	r.RoleName = field.NewString(table, "role_name")
	r.Description = field.NewString(table, "description")
	r.RoleSeq = field.NewInt64(table, "role_seq")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.ModifiedAt = field.NewTime(table, "modified_at")
	r.CreateBy = field.NewInt64(table, "create_by")
	r.ModifiedBy = field.NewInt64(table, "modified_by")

	r.fillFieldMap()

	return r
}

func (r *roleRef) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roleRef) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["role_id"] = r.RoleID
	r.fieldMap["role_name"] = r.RoleName
	r.fieldMap["description"] = r.Description
	r.fieldMap["role_seq"] = r.RoleSeq
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["modified_at"] = r.ModifiedAt
	r.fieldMap["create_by"] = r.CreateBy
	r.fieldMap["modified_by"] = r.ModifiedBy
}

func (r roleRef) clone(db *gorm.DB) roleRef {
	r.roleRefDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roleRef) replaceDB(db *gorm.DB) roleRef {
	r.roleRefDo.ReplaceDB(db)
	return r
}

type roleRefDo struct{ gen.DO }

type IRoleRefDo interface {
	gen.SubQuery
	Debug() IRoleRefDo
	WithContext(ctx context.Context) IRoleRefDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoleRefDo
	WriteDB() IRoleRefDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoleRefDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoleRefDo
	Not(conds ...gen.Condition) IRoleRefDo
	Or(conds ...gen.Condition) IRoleRefDo
	Select(conds ...field.Expr) IRoleRefDo
	Where(conds ...gen.Condition) IRoleRefDo
	Order(conds ...field.Expr) IRoleRefDo
	Distinct(cols ...field.Expr) IRoleRefDo
	Omit(cols ...field.Expr) IRoleRefDo
	Join(table schema.Tabler, on ...field.Expr) IRoleRefDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoleRefDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoleRefDo
	Group(cols ...field.Expr) IRoleRefDo
	Having(conds ...gen.Condition) IRoleRefDo
	Limit(limit int) IRoleRefDo
	Offset(offset int) IRoleRefDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoleRefDo
	Unscoped() IRoleRefDo
	Create(values ...*model.RoleRef) error
	CreateInBatches(values []*model.RoleRef, batchSize int) error
	Save(values ...*model.RoleRef) error
	First() (*model.RoleRef, error)
	Take() (*model.RoleRef, error)
	Last() (*model.RoleRef, error)
	Find() ([]*model.RoleRef, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoleRef, err error)
	FindInBatches(result *[]*model.RoleRef, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RoleRef) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoleRefDo
	Assign(attrs ...field.AssignExpr) IRoleRefDo
	Joins(fields ...field.RelationField) IRoleRefDo
	Preload(fields ...field.RelationField) IRoleRefDo
	FirstOrInit() (*model.RoleRef, error)
	FirstOrCreate() (*model.RoleRef, error)
	FindByPage(offset int, limit int) (result []*model.RoleRef, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoleRefDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roleRefDo) Debug() IRoleRefDo {
	return r.withDO(r.DO.Debug())
}

func (r roleRefDo) WithContext(ctx context.Context) IRoleRefDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roleRefDo) ReadDB() IRoleRefDo {
	return r.Clauses(dbresolver.Read)
}

func (r roleRefDo) WriteDB() IRoleRefDo {
	return r.Clauses(dbresolver.Write)
}

func (r roleRefDo) Session(config *gorm.Session) IRoleRefDo {
	return r.withDO(r.DO.Session(config))
}

func (r roleRefDo) Clauses(conds ...clause.Expression) IRoleRefDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roleRefDo) Returning(value interface{}, columns ...string) IRoleRefDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roleRefDo) Not(conds ...gen.Condition) IRoleRefDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roleRefDo) Or(conds ...gen.Condition) IRoleRefDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roleRefDo) Select(conds ...field.Expr) IRoleRefDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roleRefDo) Where(conds ...gen.Condition) IRoleRefDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roleRefDo) Order(conds ...field.Expr) IRoleRefDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roleRefDo) Distinct(cols ...field.Expr) IRoleRefDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roleRefDo) Omit(cols ...field.Expr) IRoleRefDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roleRefDo) Join(table schema.Tabler, on ...field.Expr) IRoleRefDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roleRefDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoleRefDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roleRefDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoleRefDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roleRefDo) Group(cols ...field.Expr) IRoleRefDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roleRefDo) Having(conds ...gen.Condition) IRoleRefDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roleRefDo) Limit(limit int) IRoleRefDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roleRefDo) Offset(offset int) IRoleRefDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roleRefDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoleRefDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roleRefDo) Unscoped() IRoleRefDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roleRefDo) Create(values ...*model.RoleRef) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roleRefDo) CreateInBatches(values []*model.RoleRef, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roleRefDo) Save(values ...*model.RoleRef) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roleRefDo) First() (*model.RoleRef, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleRef), nil
	}
}

func (r roleRefDo) Take() (*model.RoleRef, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleRef), nil
	}
}

func (r roleRefDo) Last() (*model.RoleRef, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleRef), nil
	}
}

func (r roleRefDo) Find() ([]*model.RoleRef, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoleRef), err
}

func (r roleRefDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoleRef, err error) {
	buf := make([]*model.RoleRef, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roleRefDo) FindInBatches(result *[]*model.RoleRef, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roleRefDo) Attrs(attrs ...field.AssignExpr) IRoleRefDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roleRefDo) Assign(attrs ...field.AssignExpr) IRoleRefDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roleRefDo) Joins(fields ...field.RelationField) IRoleRefDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roleRefDo) Preload(fields ...field.RelationField) IRoleRefDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roleRefDo) FirstOrInit() (*model.RoleRef, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleRef), nil
	}
}

func (r roleRefDo) FirstOrCreate() (*model.RoleRef, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleRef), nil
	}
}

func (r roleRefDo) FindByPage(offset int, limit int) (result []*model.RoleRef, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roleRefDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roleRefDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roleRefDo) Delete(models ...*model.RoleRef) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roleRefDo) withDO(do gen.Dao) *roleRefDo {
	r.DO = *do.(*gen.DO)
	return r
}
