// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bug_list/internal/models/model"
)

func newUserRefreshToken(db *gorm.DB, opts ...gen.DOOption) userRefreshToken {
	_userRefreshToken := userRefreshToken{}

	_userRefreshToken.userRefreshTokenDo.UseDB(db, opts...)
	_userRefreshToken.userRefreshTokenDo.UseModel(&model.UserRefreshToken{})

	tableName := _userRefreshToken.userRefreshTokenDo.TableName()
	_userRefreshToken.ALL = field.NewAsterisk(tableName)
	_userRefreshToken.ID = field.NewInt64(tableName, "id")
	_userRefreshToken.UserID = field.NewInt64(tableName, "user_id")
	_userRefreshToken.RefreashToken = field.NewString(tableName, "refreash_token")
	_userRefreshToken.AccessToken = field.NewString(tableName, "access_token")
	_userRefreshToken.ExpiredAt = field.NewTime(tableName, "expired_at")
	_userRefreshToken.CreatedAt = field.NewTime(tableName, "created_at")
	_userRefreshToken.Device = field.NewString(tableName, "device")
	_userRefreshToken.IPAddress = field.NewString(tableName, "ip_address")
	_userRefreshToken.UserAgent = field.NewString(tableName, "user_agent")

	_userRefreshToken.fillFieldMap()

	return _userRefreshToken
}

type userRefreshToken struct {
	userRefreshTokenDo

	ALL           field.Asterisk
	ID            field.Int64
	UserID        field.Int64
	RefreashToken field.String
	AccessToken   field.String
	ExpiredAt     field.Time
	CreatedAt     field.Time
	Device        field.String
	IPAddress     field.String
	UserAgent     field.String

	fieldMap map[string]field.Expr
}

func (u userRefreshToken) Table(newTableName string) *userRefreshToken {
	u.userRefreshTokenDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userRefreshToken) As(alias string) *userRefreshToken {
	u.userRefreshTokenDo.DO = *(u.userRefreshTokenDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userRefreshToken) updateTableName(table string) *userRefreshToken {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UserID = field.NewInt64(table, "user_id")
	u.RefreashToken = field.NewString(table, "refreash_token")
	u.AccessToken = field.NewString(table, "access_token")
	u.ExpiredAt = field.NewTime(table, "expired_at")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.Device = field.NewString(table, "device")
	u.IPAddress = field.NewString(table, "ip_address")
	u.UserAgent = field.NewString(table, "user_agent")

	u.fillFieldMap()

	return u
}

func (u *userRefreshToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userRefreshToken) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 9)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["refreash_token"] = u.RefreashToken
	u.fieldMap["access_token"] = u.AccessToken
	u.fieldMap["expired_at"] = u.ExpiredAt
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["device"] = u.Device
	u.fieldMap["ip_address"] = u.IPAddress
	u.fieldMap["user_agent"] = u.UserAgent
}

func (u userRefreshToken) clone(db *gorm.DB) userRefreshToken {
	u.userRefreshTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userRefreshToken) replaceDB(db *gorm.DB) userRefreshToken {
	u.userRefreshTokenDo.ReplaceDB(db)
	return u
}

type userRefreshTokenDo struct{ gen.DO }

type IUserRefreshTokenDo interface {
	gen.SubQuery
	Debug() IUserRefreshTokenDo
	WithContext(ctx context.Context) IUserRefreshTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserRefreshTokenDo
	WriteDB() IUserRefreshTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserRefreshTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserRefreshTokenDo
	Not(conds ...gen.Condition) IUserRefreshTokenDo
	Or(conds ...gen.Condition) IUserRefreshTokenDo
	Select(conds ...field.Expr) IUserRefreshTokenDo
	Where(conds ...gen.Condition) IUserRefreshTokenDo
	Order(conds ...field.Expr) IUserRefreshTokenDo
	Distinct(cols ...field.Expr) IUserRefreshTokenDo
	Omit(cols ...field.Expr) IUserRefreshTokenDo
	Join(table schema.Tabler, on ...field.Expr) IUserRefreshTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserRefreshTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserRefreshTokenDo
	Group(cols ...field.Expr) IUserRefreshTokenDo
	Having(conds ...gen.Condition) IUserRefreshTokenDo
	Limit(limit int) IUserRefreshTokenDo
	Offset(offset int) IUserRefreshTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserRefreshTokenDo
	Unscoped() IUserRefreshTokenDo
	Create(values ...*model.UserRefreshToken) error
	CreateInBatches(values []*model.UserRefreshToken, batchSize int) error
	Save(values ...*model.UserRefreshToken) error
	First() (*model.UserRefreshToken, error)
	Take() (*model.UserRefreshToken, error)
	Last() (*model.UserRefreshToken, error)
	Find() ([]*model.UserRefreshToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserRefreshToken, err error)
	FindInBatches(result *[]*model.UserRefreshToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserRefreshToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserRefreshTokenDo
	Assign(attrs ...field.AssignExpr) IUserRefreshTokenDo
	Joins(fields ...field.RelationField) IUserRefreshTokenDo
	Preload(fields ...field.RelationField) IUserRefreshTokenDo
	FirstOrInit() (*model.UserRefreshToken, error)
	FirstOrCreate() (*model.UserRefreshToken, error)
	FindByPage(offset int, limit int) (result []*model.UserRefreshToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserRefreshTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userRefreshTokenDo) Debug() IUserRefreshTokenDo {
	return u.withDO(u.DO.Debug())
}

func (u userRefreshTokenDo) WithContext(ctx context.Context) IUserRefreshTokenDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userRefreshTokenDo) ReadDB() IUserRefreshTokenDo {
	return u.Clauses(dbresolver.Read)
}

func (u userRefreshTokenDo) WriteDB() IUserRefreshTokenDo {
	return u.Clauses(dbresolver.Write)
}

func (u userRefreshTokenDo) Session(config *gorm.Session) IUserRefreshTokenDo {
	return u.withDO(u.DO.Session(config))
}

func (u userRefreshTokenDo) Clauses(conds ...clause.Expression) IUserRefreshTokenDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userRefreshTokenDo) Returning(value interface{}, columns ...string) IUserRefreshTokenDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userRefreshTokenDo) Not(conds ...gen.Condition) IUserRefreshTokenDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userRefreshTokenDo) Or(conds ...gen.Condition) IUserRefreshTokenDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userRefreshTokenDo) Select(conds ...field.Expr) IUserRefreshTokenDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userRefreshTokenDo) Where(conds ...gen.Condition) IUserRefreshTokenDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userRefreshTokenDo) Order(conds ...field.Expr) IUserRefreshTokenDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userRefreshTokenDo) Distinct(cols ...field.Expr) IUserRefreshTokenDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userRefreshTokenDo) Omit(cols ...field.Expr) IUserRefreshTokenDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userRefreshTokenDo) Join(table schema.Tabler, on ...field.Expr) IUserRefreshTokenDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userRefreshTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserRefreshTokenDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userRefreshTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserRefreshTokenDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userRefreshTokenDo) Group(cols ...field.Expr) IUserRefreshTokenDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userRefreshTokenDo) Having(conds ...gen.Condition) IUserRefreshTokenDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userRefreshTokenDo) Limit(limit int) IUserRefreshTokenDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userRefreshTokenDo) Offset(offset int) IUserRefreshTokenDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userRefreshTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserRefreshTokenDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userRefreshTokenDo) Unscoped() IUserRefreshTokenDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userRefreshTokenDo) Create(values ...*model.UserRefreshToken) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userRefreshTokenDo) CreateInBatches(values []*model.UserRefreshToken, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userRefreshTokenDo) Save(values ...*model.UserRefreshToken) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userRefreshTokenDo) First() (*model.UserRefreshToken, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRefreshToken), nil
	}
}

func (u userRefreshTokenDo) Take() (*model.UserRefreshToken, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRefreshToken), nil
	}
}

func (u userRefreshTokenDo) Last() (*model.UserRefreshToken, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRefreshToken), nil
	}
}

func (u userRefreshTokenDo) Find() ([]*model.UserRefreshToken, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserRefreshToken), err
}

func (u userRefreshTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserRefreshToken, err error) {
	buf := make([]*model.UserRefreshToken, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userRefreshTokenDo) FindInBatches(result *[]*model.UserRefreshToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userRefreshTokenDo) Attrs(attrs ...field.AssignExpr) IUserRefreshTokenDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userRefreshTokenDo) Assign(attrs ...field.AssignExpr) IUserRefreshTokenDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userRefreshTokenDo) Joins(fields ...field.RelationField) IUserRefreshTokenDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userRefreshTokenDo) Preload(fields ...field.RelationField) IUserRefreshTokenDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userRefreshTokenDo) FirstOrInit() (*model.UserRefreshToken, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRefreshToken), nil
	}
}

func (u userRefreshTokenDo) FirstOrCreate() (*model.UserRefreshToken, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserRefreshToken), nil
	}
}

func (u userRefreshTokenDo) FindByPage(offset int, limit int) (result []*model.UserRefreshToken, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userRefreshTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userRefreshTokenDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userRefreshTokenDo) Delete(models ...*model.UserRefreshToken) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userRefreshTokenDo) withDO(do gen.Dao) *userRefreshTokenDo {
	u.DO = *do.(*gen.DO)
	return u
}
