// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBugRemark = "bug_remarks"

// BugRemark mapped from table <bug_remarks>
type BugRemark struct {
	RemarkID  int64      `gorm:"column:remark_id;primaryKey;autoIncrement:true" json:"remark_id"`
	BugID     int64      `gorm:"column:bug_id;not null" json:"bug_id"`
	UserID    int64      `gorm:"column:user_id;not null" json:"user_id"`
	Remark    string     `gorm:"column:remark;not null" json:"remark"`
	CreatedAt *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName BugRemark's table name
func (*BugRemark) TableName() string {
	return TableNameBugRemark
}
