// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBug = "bugs"

// Bug mapped from table <bugs>
type Bug struct {
	BugID       int64      `gorm:"column:bug_id;primaryKey;autoIncrement:true" json:"bug_id"`
	ProjID      int64      `gorm:"column:proj_id;not null" json:"proj_id"`
	Title       string     `gorm:"column:title;not null" json:"title"`
	Description *string    `gorm:"column:description" json:"description"`
	Status      string     `gorm:"column:status;not null" json:"status"`
	Priority    *string    `gorm:"column:priority" json:"priority"`
	ReportedBy  *int64     `gorm:"column:reported_by" json:"reported_by"`
	AssignedTo  *int64     `gorm:"column:assigned_to" json:"assigned_to"`
	CreatedAt   *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	CreateBy    *int64     `gorm:"column:create_by" json:"create_by"`
	ModifiedAt  *time.Time `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy  *int64     `gorm:"column:modified_by" json:"modified_by"`
	ResolvedAt  *time.Time `gorm:"column:resolved_at" json:"resolved_at"`
}

// TableName Bug's table name
func (*Bug) TableName() string {
	return TableNameBug
}
