// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "projects"

// Project mapped from table <projects>
type Project struct {
	ProjID          int64      `gorm:"column:proj_id;primaryKey;autoIncrement:true" json:"proj_id"`
	ProjName        string     `gorm:"column:proj_name;not null" json:"proj_name"`
	ProjDescription *string    `gorm:"column:proj_description" json:"proj_description"`
	CreatedAt       *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	CreateBy        *int64     `gorm:"column:create_by" json:"create_by"`
	ModifiedAt      *time.Time `gorm:"column:modified_at" json:"modified_at"`
	ModifiedBy      *int64     `gorm:"column:modified_by" json:"modified_by"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
