// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectMember = "project_members"

// ProjectMember mapped from table <project_members>
type ProjectMember struct {
	UserID   int64      `gorm:"column:user_id;primaryKey" json:"user_id"`
	ProjID   int64      `gorm:"column:proj_id;primaryKey" json:"proj_id"`
	JoinedAt *time.Time `gorm:"column:joined_at;default:now()" json:"joined_at"`
}

// TableName ProjectMember's table name
func (*ProjectMember) TableName() string {
	return TableNameProjectMember
}
