// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoleRef = "role_ref"

// RoleRef mapped from table <role_ref>
type RoleRef struct {
	RoleID      int64      `gorm:"column:role_id;primaryKey;autoIncrement:true" json:"role_id"`
	RoleName    string     `gorm:"column:role_name;not null" json:"role_name"`
	Description *string    `gorm:"column:description" json:"description"`
	RoleSeq     *int64     `gorm:"column:role_seq" json:"role_seq"`
	CreatedAt   *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	ModifiedAt  *time.Time `gorm:"column:modified_at" json:"modified_at"`
	CreateBy    *int64     `gorm:"column:create_by" json:"create_by"`
	ModifiedBy  *int64     `gorm:"column:modified_by" json:"modified_by"`
}

// TableName RoleRef's table name
func (*RoleRef) TableName() string {
	return TableNameRoleRef
}
