// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserRefreshToken = "user_refresh_token"

// UserRefreshToken mapped from table <user_refresh_token>
type UserRefreshToken struct {
	ID            int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int64      `gorm:"column:user_id;not null" json:"user_id"`
	RefreashToken string     `gorm:"column:refreash_token;not null" json:"refreash_token"`
	AccessToken   *string    `gorm:"column:access_token" json:"access_token"`
	ExpiredAt     time.Time  `gorm:"column:expired_at;not null" json:"expired_at"`
	CreatedAt     *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	Device        *string    `gorm:"column:device" json:"device"`
	IPAddress     *string    `gorm:"column:ip_address" json:"ip_address"`
	UserAgent     *string    `gorm:"column:user_agent" json:"user_agent"`
}

// TableName UserRefreshToken's table name
func (*UserRefreshToken) TableName() string {
	return TableNameUserRefreshToken
}
