// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID     int64      `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Username   string     `gorm:"column:username;not null" json:"username"`
	Password   string     `gorm:"column:password;not null" json:"password"`
	Email      string     `gorm:"column:email;not null" json:"email"`
	Firstname  *string    `gorm:"column:firstname" json:"firstname"`
	Lastname   *string    `gorm:"column:lastname" json:"lastname"`
	CreateBy   *int64     `gorm:"column:create_by" json:"create_by"`
	ModifiedBy *int64     `gorm:"column:modified_by" json:"modified_by"`
	CreatedAt  *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	ModifiedAt *time.Time `gorm:"column:modified_at" json:"modified_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
